---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongo
resources:
  - ./mongo/ks.yaml
  - ./unifi-mongo/ks.yaml
components:
  - ../../components/common
