---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_PUSHOVER_TOKEN: '{{ .ALERTMANAGER_PUSHOVER_TOKEN }}'
        PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY }}'
        HEALTHCHECKS_IO_HEARTBEAT_URL: '{{ .HEALTHCHECKS_IO_HEARTBEAT_URL }}'
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: alertmanager
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scrape-target-zigbee
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: scrape-target-zigbee-secret
    template:
      data:
        USERNAME: '{{ .USERNAME }}'
        PASSWORD: '{{ .PASSWORD }}'
  dataFrom:
    - extract:
        key: zigbee-controller
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scrape-target-pikvm
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: scrape-target-pikvm-secret
    template:
      data:
        USERNAME: '{{ .USERNAME }}'
        PASSWORD: '{{ .PASSWORD }}'
  dataFrom:
    - extract:
        key: pikvm
