---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: internal-external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: internal-external-dns-secret
    template:
      data:
        UNIFI_USER: '{{ .UNIFI_USER }}'
        UNIFI_PASS: '{{ .UNIFI_PASS }}'
  dataFrom:
    - extract:
        key: internal-external-dns
