---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi
  namespace: network
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      app:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: 'true'
        labels: {}
        replicas: 1
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: 1
          surge: 1

        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/unifi-network-application
              tag: 9.0.114@sha256:79adf36ca9d19395b03fc3762c23478be3738fb9a62a3457b7456bc89ed60ccd
            env:
              MEM_LIMIT: '1024'
              MEM_STARTUP: '1024'
              MONGO_DBNAME: unifi
              MONGO_HOST: unifi-mongo-0.unifi-mongo-svc.mongo.svc.cluster.local
              MONGO_PASS:
                valueFrom:
                  secretKeyRef:
                    name: unifi-secret
                    key: password
              MONGO_PORT: '27017'
              MONGO_USER: unifi
              PGID: '65534'
              PUID: '65534'
              S6_READ_ONLY_ROOT: '1'
            probes:
              liveness: &probes
                enabled: true
                custom: false
              startup: *probes
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFileSystem: true
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1500Mi
                cpu: 512m
    service:
      app:
        controller: app
        type: LoadBalancer
        internalTrafficPolicy: Cluster
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: '192.168.20.5'
        ports:
          http:
            primary: true
            port: 8080
            protocol: HTTP
          stun:
            primary: false
            port: 3478
            protocol: UDP
          https:
            primary: false
            port: &port 8443
            protocol: HTTPS
          secure-redirect:
            primary: false
            port: 8843
            protocol: HTTPS
          http-redirect:
            primary: false
            port: 8880
            protocol: HTTP
          speedtest:
            primary: false
            port: 6789
            protocol: TCP
          unifi-disc:
            primary: false
            port: 10001
            protocol: UDP
          unifi-disc-12:
            primary: false
            port: 1900
            protocol: UDP
          syslog:
            primary: false
            protocol: UDP
            port: 5514
    route:
      app:
        kind: TLSRoute
        hostnames:
          - '{{ .Release.Name }}.${SECRET_DOMAIN}'
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: tls
        rules:
          - backendRefs:
              - name: *app
                port: *port
        annotations:
          hajimari.io/appName: Unifi
          hajimari.io/icon: mdi:router-network
          hajimari.io/group: servers
    persistence:
      config:
        existingClaim: unifi
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      cert:
        type: secret
        name: '${SECRET_DOMAIN/./-}-unifi'
        globalMounts:
          - path: /config/data/keystore
            subPath: keystore.jks
